services:
  # MySQL Database Service
  mysql:
    image: mysql:latest
    container_name: ivay_db
    environment:
      MYSQL_ROOT_PASSWORD: Toor.toor1 # Root password for MySQL
      MYSQL_DATABASE: TFC-E-Commerce-Ivay # Initial database to be created
      MYSQL_USER: usuarioexterno # Custom user for DB access
      MYSQL_PASSWORD: Toor.toor1 # Password for the custom user
    ports:
      - "3307:3306" # Expose internal MySQL port 3306 as 3307
    volumes:
      - mysql_data:/var/lib/mysql # Persistent volume for DB data

  # phpMyAdmin Service (for MySQL management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ivay_phpmyadmin
    environment:
      PMA_HOST: mysql # Link to MySQL container
      MYSQL_ROOT_PASSWORD: Toor.toor1 # Required for phpMyAdmin login
    ports:
      - "8080:80" # Accessible via http://localhost:8080
    depends_on:
      - mysql # Wait until MySQL is ready

  # Spring Boot Backend Service
  backend:
    build: ./ivay-backend # Uses Dockerfile in ivay-backend/
    container_name: ivay_backend
    ports:
      - "8081:8081" # Accessible via http://localhost:8081
    environment:
      DB_URL: jdbc:mysql://mysql:3306/TFC-E-Commerce-Ivay?serverTimezone=UTC&createDatabaseIfNotExist=true
      DB_USER: usuarioexterno
      DB_PASSWORD: Toor.toor1
      JWT_SECRET_KEY: 964ffdb5e95797ad2be8a036924d97a1df90a004b69e25093959be7d5104601b
    depends_on:
      - mysql # Wait until MySQL is ready

  # Frontend - Customer UI
  frontend-cliente:
    build: ./ivay-frontend # React frontend (client side)
    container_name: ivay_frontend_cliente
    ports:
      - "3000:3000" # Accessible via http://localhost:3000
    environment:
      VITE_API_BASE_URL: http://localhost:8081/api
    depends_on:
      - backend # Wait until backend is ready

  # Frontend - Admin Dashboard
  frontend-gestor:
    build: ./ivay-dashboard # React frontend (admin dashboard)
    container_name: ivay_frontend_gestor
    ports:
      - "3001:3000" # Accessible via http://localhost:3001
    environment:
      VITE_API_BASE_URL: http://localhost:8081/api
    depends_on:
      - backend # Wait until backend is ready

# Volume declaration
volumes:
  mysql_data: # Persistent storage for MySQL
